# Generated by Django 5.1.1 on 2025-06-10 17:11

import account.managers
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunSQL("CREATE EXTENSION IF NOT EXISTS unaccent;"),
        migrations.CreateModel(
            name='GlobalPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GroupProxy',
            fields=[
            ],
            options={
                'managed': False,
                'proxy': True,
            },
            bases=('auth.group',),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, db_column='tx_description', max_length=64, null=True)),
                ('icon', models.CharField(blank=True, db_column='tx_icon', max_length=64, null=True)),
                ('font_set', models.CharField(choices=[('material-icons', 'Material Icons'), ('material-icons-outlined', 'Material Icons Outlined'), ('material-icons-round', 'Material Icons Round'), ('material-icons-sharp', 'Material Icons Sharp'), ('material-icons-two', 'Material Icons Two Tone')], db_column='tx_font_set', default='material-icons', max_length=64)),
                ('route', models.CharField(blank=True, db_column='tx_route', max_length=64, null=True)),
            ],
            options={
                'db_table': 'account_menu',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, db_column='tx_description', max_length=64, null=True, unique=True)),
                ('icon', models.CharField(blank=True, db_column='tx_icon', max_length=64, null=True)),
                ('is_active', models.BooleanField(db_column='cs_active', default=True)),
                ('menu', models.BooleanField(db_column='cs_menu', default=True, null=True)),
            ],
            options={
                'db_table': 'account_module',
                'permissions': (('load_module', 'Can load module'),),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_column='tx_username', max_length=64, unique=True)),
                ('password', models.CharField(db_column='tx_password', max_length=104)),
                ('name', models.CharField(db_column='tx_name', max_length=256, null=True)),
                ('email', models.CharField(db_column='tx_email', max_length=256, null=True)),
                ('last_login', models.DateTimeField(db_column='dt_last_login', null=True)),
                ('is_active', models.BooleanField(db_column='cs_active', default=True)),
                ('is_superuser', models.BooleanField(db_column='cs_superuser', default=False, null=True)),
                ('is_staff', models.BooleanField(db_column='cs_staff', default=False, null=True)),
                ('is_default', models.BooleanField(db_column='cs_default', default=False, null=True)),
                ('avatar', models.BinaryField(db_column='bl_avatar', null=True)),
                ('is_ad_user', models.BooleanField(db_column='cs_is_ad_user', default=False)),
                ('is_privileged_user', models.BooleanField(db_column='cs_is_privileged_user', null=True)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', account.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AccountUserGroup',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('group', models.ForeignKey(db_column='id_group', on_delete=django.db.models.deletion.DO_NOTHING, related_name='account_user_groups', to='auth.group')),
                ('user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.DO_NOTHING, related_name='account_user_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account_user_groups',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', through='account.AccountUserGroup', to='auth.group', verbose_name='groups'),
        ),
        migrations.CreateModel(
            name='GroupExtraFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_column='tx_code', max_length=64, unique=True)),
                ('group', models.OneToOneField(db_column='id_group', on_delete=django.db.models.deletion.CASCADE, related_name='group_extra_fields', to='auth.group')),
            ],
            options={
                'db_table': 'group_extra_fields',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LoggedInUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_token', models.CharField(blank=True, max_length=10000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logged_in_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account_logged_in_user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ModuleMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(db_column='nb_order', null=True)),
                ('has_divider', models.BooleanField(db_column='cs_divisor', default=False)),
                ('is_active', models.BooleanField(db_column='cs_active', default=True)),
                ('menu', models.ForeignKey(db_column='id_menu', on_delete=django.db.models.deletion.CASCADE, related_name='module_menus', to='account.menu')),
                ('module', models.ForeignKey(db_column='id_module', on_delete=django.db.models.deletion.CASCADE, related_name='module_menus', to='account.module')),
                ('root', models.ForeignKey(db_column='id_root', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='account.menu')),
            ],
            options={
                'db_table': 'account_module_menu',
                'permissions': (('load_module_menu', 'Can load module menu'),),
                'managed': True,
                'unique_together': {('module', 'menu')},
            },
        ),
    ]
