# Generated by Django 5.1.1 on 2025-06-10 17:11

from django.db import migrations

from account.models import User


def create_initial_user(apps, schema_editor):
    User.objects.create_superuser(
        username='admin',
        password='123456',
        name='Administrator',
        is_default=True
    )


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_user)
    ]
